version: '3.8'

services:
  yt-dlp-web:
    build: .
    container_name: yt-dlp-web
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      # 下载文件持久化存储（使用命名卷避免权限问题）
      - downloads:/app/downloads
      # 配置文件持久化（可选）
      - config:/app/config
    environment:
      # 管理员账号配置
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin123
      # 下载文件夹配置
      - DOWNLOAD_FOLDER=/app/downloads
      # Flask密钥（生产环境请修改）
      - SECRET_KEY=your-secret-key-change-in-production
      # 时区设置
      - TZ=Asia/Shanghai
    networks:
      - yt-dlp-network
    labels:
      # Portainer标签
      - "traefik.enable=true"
      - "traefik.http.routers.yt-dlp.rule=Host(`yt-dlp.local`)"
      - "traefik.http.services.yt-dlp.loadbalancer.server.port=8080"
      # 应用信息
      - "app.name=yt-dlp-web"
      - "app.description=YouTube下载器Web界面"
      - "app.version=1.0.0"

networks:
  yt-dlp-network:
    driver: bridge

volumes:
  downloads:
    driver: local
  config:
    driver: local
