version: '3.8'

services:
  yt-dlp-web:
    image: yt-dlp-web:latest
    container_name: yt-dlp-web
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      # 下载文件持久化存储
      - yt-dlp-downloads:/app/downloads
      # 配置文件持久化
      - yt-dlp-config:/app/config
    environment:
      # 管理员账号配置（请修改默认密码）
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin123
      # 下载文件夹配置
      - DOWNLOAD_FOLDER=/app/downloads
      # Flask密钥（生产环境请修改）
      - SECRET_KEY=your-secret-key-change-in-production-environment
      # 时区设置
      - TZ=Asia/Shanghai
      # 清理配置
      - AUTO_CLEANUP_ENABLED=true
      - FILE_RETENTION_HOURS=24
      - MAX_STORAGE_MB=2048
      - KEEP_RECENT_FILES=20
    networks:
      - yt-dlp-network
    labels:
      # Portainer管理标签
      - "io.portainer.accesscontrol.teams=administrators"
      - "io.portainer.accesscontrol.users=admin"
      # 应用信息标签
      - "app.name=yt-dlp-web"
      - "app.description=YouTube视频下载器Web界面"
      - "app.version=1.0.0"
      - "app.category=media"
      - "app.url=http://localhost:8080"
      # 健康检查标签
      - "health.check.url=http://localhost:8080/"
      - "health.check.interval=30s"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  yt-dlp-network:
    driver: bridge
    labels:
      - "app.network=yt-dlp"

volumes:
  yt-dlp-downloads:
    driver: local
    labels:
      - "app.volume=downloads"
      - "app.description=YouTube下载文件存储"
  yt-dlp-config:
    driver: local
    labels:
      - "app.volume=config"
      - "app.description=应用配置文件存储"
